# Generated by Django 2.2.4 on 2019-08-03 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_first_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='bar.Product'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AlterField(
            model_name='user',
            name='second',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='bar.Product'),
        ),
        migrations.AlterField(
            model_name='user',
            name='third',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='bar.Product'),
        ),
    ]
